name: QArunBackTestsV3

on:
  push:
    branches:
      - 'QA'

jobs:
  acciones_condicionales:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Ejecutar pruebas unitarias
        run: |
          cd BACK/hu-tp-01-001
          npm install
          npm test 2>&1 | tee test-results-hu-tp-01-001.log || true

          cd BACK/hu-tp-02-001
          npm install
          npm test 2>&1 | tee test-results-hu-tp-02-001.log || true
          
      
      - name: Resultados
        run: |
          echo "RESULTADO - hu-tp-01-001:"
          cat BACK/hu-tp-01-001/test-results-hu-tp-01-001.log
          echo "-----------------------------------------"
          
          echo "RESULTADO - hu-tp-02-001:"
          cat BACK/hu-tp-02-001/test-results-hu-tp-02-001.log
          echo "-----------------------------------------"
      
